apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-demo.fullname" . }}
  labels:
    {{- include "springboot-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "springboot-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/color: {{ .Values.activeColor }}
---
{{- range $color, $config := .Values.colors }}
{{- if $config.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-demo.fullname" $ }}-{{ $color }}
  labels:
    {{- include "springboot-demo.labels" $ | nindent 4 }}
    app.kubernetes.io/color: {{ $color }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "springboot-demo.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/color: {{ $color }}
---
{{- end }}
{{- end }}

