apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitea-admin/platform-gitops.git
    targetRevision: main
    path: apps/harbor
    helm:
      releaseName: harbor
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

