apiVersion: v2
name: jenkins
description: Jenkins managed by Argo CD
type: application
version: 0.1.0
appVersion: "2.555.3"
dependencies:
  - name: jenkins
    version: 5.9.29
    repository: file://charts/jenkins

