replicaCount: 1

image:
  repository: harbor.example.com/external/sonatype/nexus3
  tag: "3.93.2"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-regcred

service:
  type: ClusterIP
  port: 8081

persistence:
  enabled: true
  storageClass: csi-cinder-sc-retain
  accessMode: ReadWriteOnce
  size: 100Gi

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

javaOpts: >-
  -Xms1g
  -Xmx1g
  -XX:MaxDirectMemorySize=1g
  -Djava.util.prefs.userRoot=/nexus-data/javaprefs

httpRoute:
  enabled: false
  name: nexus-route
  hostnames:
    - nexus.example.com
  parentRefs:
    - name: service-gateway
      namespace: istio-ingress
      sectionName: http

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
